package com.example.sportevent.data.model.entities;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class Participant implements Serializable{

    // Todo: id should be auto generated by database
    private int id;
    private String name;
    private String email;
    private String address;
    private String phoneNumber;
    private List<String> joinedEventListId;
    private List<String> finishedEventListId;
    private Result result;


    public Participant(int id, String name, String email, String address, String phoneNumber) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.address = address;
        this.phoneNumber = phoneNumber;
    }

    public Participant(String name, String email, String address, String phoneNumber, List<String> joinedEventListId, List<String> finishedEventListId, Result result) {
        this.name = name;
        this.email = email;
        this.address = address;
        this.phoneNumber = phoneNumber;
        this.joinedEventListId = joinedEventListId;
        this.finishedEventListId = finishedEventListId;
        this.result = result;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }

    public String getAddress() {
        return address;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }


    public Result getResult() {
        return result;
    }


}
