package com.example.sportevent.data.model.entities;

import java.util.ArrayList;

public class Participant {

    // Todo: id should be auto generated by database
    private int id;
    private String name;
    private String email;
    private String address;
    private String phoneNumber;
    private ArrayList<Event> joinedEventList;
    private ArrayList<Event> finishedEventList;
    private Result result;


    public Participant(int id, String name, String email, String address, String phoneNumber) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.address = address;
        this.phoneNumber = phoneNumber;
    }

    public Participant(int id, String name, String email, String address, String phoneNumber, ArrayList<Event> joinedEventList, ArrayList<Event> finishedEventList, Result result) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.address = address;
        this.phoneNumber = phoneNumber;
        this.joinedEventList = joinedEventList;
        this.finishedEventList = finishedEventList;
        this.result = result;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }

    public String getAddress() {
        return address;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public ArrayList<Event> getJoinedEventList() {
        return joinedEventList;
    }

    public ArrayList<Event> getFinishedEventList() {
        return finishedEventList;
    }

    public Result getResult() {
        return result;
    }
}
