package com.example.sportevent.data;

import android.widget.TextView;

public class Participant {

    // Todo: id should be auto generated by database
    private int id;
    private String name;
    private String email;
    private String address;
    private String phoneNumber;

    public Participant(int id, String name, String email, String address, String phoneNumber) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.address = address;
        this.phoneNumber = phoneNumber;
    }

    public Participant(String navn, String email, String address, String phone) {
        this.name = navn;
        this.email = email;
        this.address = address;
        this.phoneNumber = phone;
    }

    public int getId() {
        return id;
    }
    public void setName(String Name) {
        this.name = Name;
    }

    public String getName() {
        return name;
    }
    public void setEmail(String Email) {
        this.email = Email;
    }
    public String getEmail() {
        return email;
    }
    public void setAddress(String Address) {
        this.address = Address;
    }
    public String getAddress() {
        return address;
    }
    public void setPhoneNumber(String PhoneNumber) {
        this.phoneNumber = PhoneNumber;
    }
    public String getPhoneNumber() {
        return phoneNumber;
    }
}
